apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python application that displays time.
  annotations:
    github.com/project-slug: MohanDevarajan/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: Development
  lifecycle: experimental
